services:
    db:
        image: postgres:14.3-alpine3.15
        volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Инициализация
        - ./db/migrations:/migrations 
        ports: 
            - "5431:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}